# https://github.com/softwaresaved/build_and_test_examples/blob/master/travis/Languages.md
language: cpp

### for C++11 
# https://docs.travis-ci.com/user/installing-dependencies/
# http://jsteemann.github.io/blog/2014/10/17/using-travis-ci-for-a-c-plus-plus-11-project/


compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

### End of for C++11

script:
  - make
